name: Release Go project

on:
  push:
    tags:
      - "*"
    branches:
      - "build-test"

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go 1.20.4
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.4
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --config=build/.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.OPEN_METRICS_RELEASE_TOKEN }}

          